---

- hosts: all
  become: true
  tasks:


  - name: update  repository index for Ubuntu
    apt:
      update_cache: yes
   when: ansible_distribution_version == "Ubuntu"

  - name: install apache2 and php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu" 

  - name: update repository index for CentOOS
    dnf:
      update_cache: yes
   when: ansible_ distribution_version == "CentOS"

  - name: install apache and php packages for CentOS
    dnf:
      name:
        - httpd
        - php
     state: latest
   when: ansible_distribution == "CentOS" 
